"""initial tables

Revision ID: 88dfeade80de
Revises: 
Create Date: 2026-07-09 12:05:51.951747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dfeade80de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutual_funds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_name', sa.String(length=150), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amc_name', sa.String(length=100), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pan'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_table('nav_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('nav', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('snapshot_type', sa.String(length=5), nullable=False),
    sa.Column('market_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_id', 'market_date', 'snapshot_type', name='uq_nav_fund_date_type')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('units_held', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('avg_nav', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sip_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sip_date', sa.SmallInteger(), nullable=False),
    sa.Column('sip_payments_made', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['mutual_funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fund_id', name='uq_portfolio_user_fund')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolios')
    op.drop_table('nav_snapshots')
    op.drop_table('call_logs')
    op.drop_table('users')
    op.drop_table('mutual_funds')
    # ### end Alembic commands ###
